fix(kafkactl): add missing no_security_context=False (#138)
`kafkactl` subcommand was broken since
https://github.com/getsentry/sentry-infra-tools/pull/136
```
TypeError: run_pod() missing 1 required positional argument: 'no_security_context'
```