feat(render-services): Add an option to render services fast (#82)
Adds a `--fast` option to only render the specified services instead of
checking all services in the cluster for changes. Very useful for local
development.

Without this commit:

```
└─ % python -m sentry_kube.render_services k8s/services/relay/
Service unchanged: s4s : default : common
Service unchanged: s4s : default : arroyo
Service unchanged: s4s : default : memcached
Service unchanged: s4s : default : redis
Service unchanged: s4s : default : chartcuterie
Service unchanged: s4s : default : datadog-cluster-agent
Service unchanged: s4s : default : geoipupdate
Service unchanged: s4s : default : iap-ingress
Service unchanged: s4s : default : injector
Service unchanged: s4s : default : kafkactl
Service unchanged: s4s : default : mesh
Service unchanged: s4s : default : redash
Service materialized: s4s : default : relay
Service unchanged: s4s : default : relay-pop
Service unchanged: s4s : default : salt
Service unchanged: s4s : default : seer
Service unchanged: s4s : default : seer-gpu
Service unchanged: s4s : default : topicctl
Service unchanged: s4s : default : uptime-checker
Service unchanged: s4s : default : usage-accountant
Service unchanged: s4s : default : vector
Service unchanged: s4s : default : vector-uc
Service unchanged: s4s : default : veneur
Service unchanged: s4s : default : vroom
Service unchanged: s4s : default : frontend
Service unchanged: s4s : default : keda-auth
Service unchanged: s4s : default : getsentry
Service unchanged: s4s : default : pgbouncer
Service unchanged: s4s : default : snuba
Service unchanged: s4s : default : super-big-consumers
Service unchanged: s4s : default : symbolicator
Service unchanged: saas : default : analytics
Service unchanged: saas : default : catalog-sync
Service unchanged: saas : default : certbot
Service unchanged: saas : default : chartcuterie
Service unchanged: saas : default : cleanup-getsentry
Service unchanged: saas : default : common
Service unchanged: saas : default : consul
Service unchanged: saas : default : datadog-cluster-agent
Service unchanged: saas : default : descheduler
Service unchanged: saas : default : frontend
Service unchanged: saas : default : geoipupdate
Service unchanged: saas : default : getsentry
Service unchanged: saas : default : getsentry-control
Service unchanged: saas : default : github-deployment-gate
Service unchanged: saas : default : iap-ingress
Service unchanged: saas : default : injector
Service unchanged: saas : default : kafkactl
Service unchanged: saas : default : keda-auth
Service unchanged: saas : default : lb-cert-update
Service unchanged: saas : default : mesh
Service unchanged: saas : default : mcrouter
Service unchanged: saas : default : nodestore
Service unchanged: saas : default : orbital
Service unchanged: saas : default : pgbouncer
Service unchanged: saas : default : pypi-proxy
Service unchanged: saas : default : redash
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/dav1d/sentry/ops/.venv-sentry-kube/lib/python3.11/site-packages/sentry_kube/render_services.py", line 72, in <module>
    render_services()
  File "/Users/dav1d/sentry/ops/.venv-sentry-kube/lib/python3.11/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dav1d/sentry/ops/.venv-sentry-kube/lib/python3.11/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/dav1d/sentry/ops/.venv-sentry-kube/lib/python3.11/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dav1d/sentry/ops/.venv-sentry-kube/lib/python3.11/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dav1d/sentry/ops/.venv-sentry-kube/lib/python3.11/site-packages/sentry_kube/render_services.py", line 49, in render_services
    changed = materialize(
              ^^^^^^^^^^^^
  File "/Users/dav1d/sentry/ops/.venv-sentry-kube/lib/python3.11/site-packages/libsentrykube/kube.py", line 286, in materialize
    render_templates(
  File "/Users/dav1d/sentry/ops/.venv-sentry-kube/lib/python3.11/site-packages/libsentrykube/kube.py", line 254, in render_templates
    rendered = env.get_template(path).render(render_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dav1d/sentry/ops/.venv-sentry-kube/lib/python3.11/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/dav1d/sentry/ops/.venv-sentry-kube/lib/python3.11/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/dav1d/sentry/ops/k8s/services/relay/deployment.yaml", line 134, in top-level template code
    - {{ envoy_sidecar(
^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dav1d/sentry/ops/.venv-sentry-kube/lib/python3.11/site-packages/jinja2/environment.py", line 487, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'limits'
```

With the commit:

```
└─ % python -m sentry_kube.render_services --fast k8s/services/relay/
Service unchanged: goldmansachs : default : relay
Service unchanged: geico : default : relay
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/dav1d/sentry/ops/.venv-sentry-kube/lib/python3.11/site-packages/sentry_kube/render_services.py", line 78, in <module>
    render_services()
  File "/Users/dav1d/sentry/ops/.venv-sentry-kube/lib/python3.11/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dav1d/sentry/ops/.venv-sentry-kube/lib/python3.11/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/dav1d/sentry/ops/.venv-sentry-kube/lib/python3.11/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dav1d/sentry/ops/.venv-sentry-kube/lib/python3.11/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dav1d/sentry/ops/.venv-sentry-kube/lib/python3.11/site-packages/sentry_kube/render_services.py", line 55, in render_services
    changed = materialize(
              ^^^^^^^^^^^^
  File "/Users/dav1d/sentry/ops/.venv-sentry-kube/lib/python3.11/site-packages/libsentrykube/kube.py", line 286, in materialize
    render_templates(
  File "/Users/dav1d/sentry/ops/.venv-sentry-kube/lib/python3.11/site-packages/libsentrykube/kube.py", line 254, in render_templates
    rendered = env.get_template(path).render(render_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dav1d/sentry/ops/.venv-sentry-kube/lib/python3.11/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/dav1d/sentry/ops/.venv-sentry-kube/lib/python3.11/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/dav1d/sentry/ops/k8s/services/relay/deployment.yaml", line 134, in top-level template code
    - {{ envoy_sidecar(
^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dav1d/sentry/ops/.venv-sentry-kube/lib/python3.11/site-packages/jinja2/environment.py", line 487, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'limits'
```